* Installing on a new machine

On a new machine, do the following:
1. Install NixOS on a flashdrive. Replace "sdX" with correct device name
   #+begin_src shell
     dd if=path-to-image of=/dev/sdX status=progress
   #+end_src

2. Create the machine-specific configuration, see =machine/= for examples.

3. Boot the new machine onto the flashdrive. Booting onto a flashdrive is
   machine specific. Search it.

4. Get my scripts
   #+begin_src shell
     git clone https://github.com/iowaguy/dotfiles workspace/areas/system-management/dotfiles/
   #+end_src

5. Run my installer script
   #+begin_src shell
     cd home/programs/mynix
     sudo ./mynix fresh
   #+end_src

6. Reboot

7. Run post-install script
  #+begin_src shell
    git clone https://github.com/iowaguy/dotfiles ~/workspace/areas/system-management/dotfiles
    cd /persist/home/ben/workspace/areas/system-management/dotfiles/home/programs/mynix
    ./mynix install
  #+end_src

8. Add new machine's =syncthing= ID to the devices in the [[file:system/configuration.nix::syncthing = {][configuration.nix]],
   and add the device names to the list of devices to sync for each dir.

9. Trust GPG key. The =GPG-ID= is the last 12 characters of the fingerprint
   from =gpg -k=.
   #+begin_src shell
    gpg --edit-key <KEY_ID>
    gpg> trust
   #+end_src

10. Setup =pass=
   #+begin_src shell
     git clone git@github.com:iowaguy/passwords.git ~/.password-store
     pass init <GPG-ID>
   #+end_src

11. Install =doom-emacs=
  #+begin_src shell
    git clone https://github.com/hlissner/doom-emacs ~/.emacs.d
    ~/.emacs.d/bin/doom install
  #+end_src

12. Generate ssh key
    #+begin_src shell
      ssh-keygen -t ed25519 -C "ben@<HOSTNAME>"
    #+end_src

13. install [[https://github.com/retorquere/zotero-better-bibtex/][Better BibTeX]]
14. Follow installation instructions [[https://retorque.re/zotero-better-bibtex/installation/][here]].
install [[http://zotfile.com/][zotfile]] plugin for zotero
- use zotfile to rename all pdfs the same as their cite key
  - go to tools -> ZotFile preferences -> renaming rules -> set format to =%b=

export references to bibtex via zotero:
- File > Export Libarary > Keep Updated > /home/ben/workspace/projects/zettelkasten/references.bib

** Debugging install
If you get an error when creating the zpool that looks like =/dev/sda2 is part
of the exported pool 'rpool'=, run the following, and then try again.
#+begin_src shell
  sudo zpool labelclear -f rpool
#+end_src

If there is already a pool with the same name, it may be necessary to zero the
disk, like so:
#+begin_src shell
  sudo dd if=/dev/zero of=<DEVICE> bs=16M status=progress
#+end_src

* Icons
To find icons, use =gucharmap=.

#+begin_src shell
  nix-shell -p gnome.gucharmap --run gucharmap
#+end_src
Use =ctrl-f= to find the glyph, then right click on the icon to show what font
