* Installing on a new machine

On a new machine, do the following:
1. Install NixOS on a flashdrive. Replace "sdX" with correct device name
   #+begin_src shell
     dd if=path-to-image of=/dev/sdX status=progress
   #+end_src

2. Create the machine-specific configuration, see =machine/= for examples.

3. Boot the new machine onto the flashdrive. Booting onto a flashdrive is
   machine specific. Search it.

4. Get my scripts
   #+begin_src shell
     git clone https://github.com/iowaguy/dotfiles
   #+end_src

5. Run my installer script
   #+begin_src shell
     cd home/programs/mynix
     sudo ./mynix fresh
   #+end_src

6. Reboot

7. Log into root, set password for my user
   #+begin_src shell
     passwd ben
   #+end_src

   To logout in =i3=, hit =Alt+Mod+e=.

8. Update machine config symlink
   #+begin_src shell
     rm /etc/nixos/machine/current.nix
   #+end_src

9. Clone this repo into =~/workspace=.

10. Run post-install script
   #+begin_src shell
     cd ~/workspace/dotfiles/home/programs/mynix
     ./mynix install
   #+end_src

11. Add new machine's =syncthing= ID to the devices in the [[file:system/configuration.nix::syncthing = {][configuration.nix]],
    and add the device names to the list of devices to sync for each dir.

12. Setup =pass=. The =GPG-ID= is the last 12 characters of the fingerprint from
    =gpg -k=.
   #+begin_src shell
     git clone git@github.com:iowaguy/passwords.git ~/.password-store
     pass init <GPG-ID>
   #+end_src

** Debugging install
If you get an error when creating the zpool that looks like =/dev/sda2 is part
of the exported pool 'bpool_xxxx'=, run the following, and then try again.
#+begin_src shell
  sudo zpool labelclear -f bpool_xxxx
#+end_src

If there is already a pool with the same name, it may be necessary to zero the
disk, like so:
#+begin_src shell
  sudo dd if=/dev/zero of=<DEVICE> bs=16M status=progress
#+end_src
