#+OPTIONS: toc:nil num:nil

** iowaguy's dotfiles
Mostly borrowed from [[https://github.com/hrs][hrs]]

I'm currently running MacOS on a 2015 MacBook Pro. I mostly use [[https://www.mozilla.org/en-US/firefox/][Firefox]] and [[https://www.gnu.org/software/emacs/][Emacs]].

** [[https://github.com/hrs][hrs]]'s comments

I hope you like fiddling with your =.emacs.d= ad nauseam, 'cause I obviously do.

You're probably here for my literate [[./emacs/.emacs.d/configuration.org][Emacs config]]! Most of my time is spent in
either Emacs or Firefox. I think a text editor is just a terrific environment
for editing text, so I use Emacs for all kinds of things that "normal" people
use specialized tools for, including:

- Task management and general writing with [[https://orgmode.org/][Org]],
- Email browsing with [[https://www.djcbsoftware.nl/code/mu/mu4e.html][mu4e]], backed by:
  - [[http://isync.sourceforge.net/][mbsync]] for synchronization over IMAP,
  - [[https://marlam.de/msmtp/][msmtp]] for sending messages over SMTP,
  - [[https://github.com/djcb/mu][mu]] for managing a local searchable index,
  - [[https://gnupg.org/][gpg]] for encryption and signatures,
- Git with [[https://magit.vc/][magit]], and
- File management with [[https://www.gnu.org/software/emacs/manual/html_node/emacs/Dired.html][dired]] and [[https://github.com/jwiegley/emacs-async][async]].

I also use some non-Emacs tools! I like:
- a hodgepodge of [[https://www.signal.org/][Signal]], [[https://telegram.org/][Telegram]], [[https://www.skype.com/en/][Skype]], [[https://zoom.us/][Zoom]], and [[https://slack.com/][Slack]] for synchronous
  communication. I can't say I really /like/ any of them, aside from Signal
  (most of the time), but network effects mean the matter's mostly out of my
  hands.

This whole repository isn't /really/ intended for anyone's use but my own, and
of course it's catered to my way of doing things, so, you know, be prepared for
that.

Enjoy! =)

*** Installation

Clone this thing wherever you like (I use =~/.dotfiles=) and run the
=install.sh= script. That will:

- Install a bunch of Debian packages,
- Set up a bunch of symlinks in your home directory (e.g., =~/.bashrc= →
  =~/.dotfiles/bash/.bashrc=), and
- Install a handful of required Ruby gems.

It (mostly) won't overwrite existing files, so move those out of the way first.
