#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

# Kill any running processes, -x option searches for an exact match
if pgrep -x mbsync; then
  pkill -x mbsync
fi
if pgrep -x mu; then
  pkill -x mu
fi

# Fetch new mail
/usr/local/bin/mbsync personal

# Index new mail
/usr/local/bin/mu index --nocolor
